# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/proto/neopixel.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='src/proto/neopixel.proto',
  package='viam.components.neopixel.v1',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x18src/proto/neopixel.proto\x12\x1bviam.components.neopixel.v1\x1a\x1cgoogle/api/annotations.proto\"V\n\x14SetPixelColorRequest\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n\x05index\x18\x02 \x01(\x05R\x05index\x12\x14\n\x05\x63olor\x18\x03 \x01(\x05R\x05\x63olor\"1\n\x15SetPixelColorResponse\x12\x18\n\x07success\x18\x01 \x01(\x08R\x07success\"!\n\x0bShowRequest\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\"(\n\x0cShowResponse\x12\x18\n\x07success\x18\x01 \x01(\x08R\x07success2\xd9\x02\n\x0fNeopixelService\x12\xb4\x01\n\rSetPixelColor\x12\x31.viam.components.neopixel.v1.SetPixelColorRequest\x1a\x32.viam.components.neopixel.v1.SetPixelColorResponse\"<\x82\xd3\xe4\x93\x02\x36\"4/acme/api/v1/service/neopixel/{name}/set_pixel_color\x12\x8e\x01\n\x04Show\x12(.viam.components.neopixel.v1.ShowRequest\x1a).viam.components.neopixel.v1.ShowResponse\"1\x82\xd3\xe4\x93\x02+\")/acme/api/v1/service/neopixel/{name}/showb\x06proto3'
  ,
  dependencies=[google_dot_api_dot_annotations__pb2.DESCRIPTOR,])




_SETPIXELCOLORREQUEST = _descriptor.Descriptor(
  name='SetPixelColorRequest',
  full_name='viam.components.neopixel.v1.SetPixelColorRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='viam.components.neopixel.v1.SetPixelColorRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='name', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='index', full_name='viam.components.neopixel.v1.SetPixelColorRequest.index', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='index', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='color', full_name='viam.components.neopixel.v1.SetPixelColorRequest.color', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='color', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=173,
)


_SETPIXELCOLORRESPONSE = _descriptor.Descriptor(
  name='SetPixelColorResponse',
  full_name='viam.components.neopixel.v1.SetPixelColorResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='viam.components.neopixel.v1.SetPixelColorResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='success', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=175,
  serialized_end=224,
)


_SHOWREQUEST = _descriptor.Descriptor(
  name='ShowRequest',
  full_name='viam.components.neopixel.v1.ShowRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='viam.components.neopixel.v1.ShowRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='name', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=226,
  serialized_end=259,
)


_SHOWRESPONSE = _descriptor.Descriptor(
  name='ShowResponse',
  full_name='viam.components.neopixel.v1.ShowResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='viam.components.neopixel.v1.ShowResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='success', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=261,
  serialized_end=301,
)

DESCRIPTOR.message_types_by_name['SetPixelColorRequest'] = _SETPIXELCOLORREQUEST
DESCRIPTOR.message_types_by_name['SetPixelColorResponse'] = _SETPIXELCOLORRESPONSE
DESCRIPTOR.message_types_by_name['ShowRequest'] = _SHOWREQUEST
DESCRIPTOR.message_types_by_name['ShowResponse'] = _SHOWRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SetPixelColorRequest = _reflection.GeneratedProtocolMessageType('SetPixelColorRequest', (_message.Message,), {
  'DESCRIPTOR' : _SETPIXELCOLORREQUEST,
  '__module__' : 'src.proto.neopixel_pb2'
  # @@protoc_insertion_point(class_scope:viam.components.neopixel.v1.SetPixelColorRequest)
  })
_sym_db.RegisterMessage(SetPixelColorRequest)

SetPixelColorResponse = _reflection.GeneratedProtocolMessageType('SetPixelColorResponse', (_message.Message,), {
  'DESCRIPTOR' : _SETPIXELCOLORRESPONSE,
  '__module__' : 'src.proto.neopixel_pb2'
  # @@protoc_insertion_point(class_scope:viam.components.neopixel.v1.SetPixelColorResponse)
  })
_sym_db.RegisterMessage(SetPixelColorResponse)

ShowRequest = _reflection.GeneratedProtocolMessageType('ShowRequest', (_message.Message,), {
  'DESCRIPTOR' : _SHOWREQUEST,
  '__module__' : 'src.proto.neopixel_pb2'
  # @@protoc_insertion_point(class_scope:viam.components.neopixel.v1.ShowRequest)
  })
_sym_db.RegisterMessage(ShowRequest)

ShowResponse = _reflection.GeneratedProtocolMessageType('ShowResponse', (_message.Message,), {
  'DESCRIPTOR' : _SHOWRESPONSE,
  '__module__' : 'src.proto.neopixel_pb2'
  # @@protoc_insertion_point(class_scope:viam.components.neopixel.v1.ShowResponse)
  })
_sym_db.RegisterMessage(ShowResponse)



_NEOPIXELSERVICE = _descriptor.ServiceDescriptor(
  name='NeopixelService',
  full_name='viam.components.neopixel.v1.NeopixelService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=304,
  serialized_end=649,
  methods=[
  _descriptor.MethodDescriptor(
    name='SetPixelColor',
    full_name='viam.components.neopixel.v1.NeopixelService.SetPixelColor',
    index=0,
    containing_service=None,
    input_type=_SETPIXELCOLORREQUEST,
    output_type=_SETPIXELCOLORRESPONSE,
    serialized_options=b'\202\323\344\223\0026\"4/acme/api/v1/service/neopixel/{name}/set_pixel_color',
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Show',
    full_name='viam.components.neopixel.v1.NeopixelService.Show',
    index=1,
    containing_service=None,
    input_type=_SHOWREQUEST,
    output_type=_SHOWRESPONSE,
    serialized_options=b'\202\323\344\223\002+\")/acme/api/v1/service/neopixel/{name}/show',
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_NEOPIXELSERVICE)

DESCRIPTOR.services_by_name['NeopixelService'] = _NEOPIXELSERVICE

# @@protoc_insertion_point(module_scope)
