# see https://github.com/viamrobotics/build-action for help
on:
  push:
    tags:
    - '[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:
    inputs:
      version:
        description: "Optionally pass in version when running manually"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: viamrobotics/build-action@v1
      with:
        # note: you can replace this line with 'version: ""' if you want to test the build process without deploying
        version: ${{ github.event_name == 'push' && github.ref_name || inputs.version }}
        ref: ${{ github.sha }}
        key-id: ${{ secrets.viam_key_id }}
        key-value: ${{ secrets.viam_key_value }}